version: 2
jobs:
  build:
    working_directory: ~/tuhi
    docker:
      - image: fedora:latest
    steps:
      - run:
          command: |
            dnf install -y meson gettext python3-devel pygobject3-devel python3-flake8 desktop-file-utils libappstream-glib
      - checkout
      - run:
          command: |
            meson builddir
            ninja -C builddir test
      - store_artifacts:
          path: ~/tuhi/builddir/meson-logs

